---
name: Lingua-DE-Wortschatz
version: 1.23
author:
  - Daniel Schroeer <daniel.schroeer@physik.uni-muenchen.de>
abstract: ~
license: perl
requires:
  Encode: 0
  Exporter: 0
  HTML::Entities: 0
  SOAP::Lite: 0
  Text::Autoformat: 0
provides:
  Lingua::DE::Wortschatz:
    file: lib/Lingua/DE/Wortschatz.pm
    version: 1.21009
  Lingua::DE::Wortschatz::Result:
    file: lib/Lingua/DE/Wortschatz.pm
    version: 1.21009
generated_by: Module::Build version 0.2611
